SPIRV-Tools: Autospec creation for update from version 61dfd8492b6e324f684863ecbd79c299a06e6517 to version 2019.3
Alan Baker (1):
      Reverting commit da5a780ff9fff7e226ca84728075adabc4d1608c

Clouds (1):
      fix example.cpp (#2540)

David Neto (6):
      Repair test for unused storage buffer with descriptor (#2436)
      README: fix formatting of requiring Python 'future' (#2500)
      SPIRV-Tools requires python3 (#2510)
      Support SPIR-V 1.4 (#2550)
      spvtest::Validate::CompileFailure: Don't leak the diagnostic (#2564)
      VK_KHR_uniform_buffer_standard_layout validation (#2562)

Diego Novillo (1):
      Fix clang-tidy warning about definition/declaration mismatch. (#2571)

Ehsan (3):
      Allow NonWritable to target struct members. (#2420)
      [spirv] Package and upload builds. (#2544)
      Update README with links to build artifacts. (#2548)

François Bertel (1):
      Fixed undefined reference to 'clock_gettime' by linking rt library (#2409)

Gustavo Alvarez (1):
      Add spirv-lesspipe.sh into SPIRV_SKIP_EXECUTABLES umbrella (https://github.com/KhronosGroup/SPIRV-Tools/issues/2497) (#2504)

Jaebaek Seo (1):
      Validator: no Storage comparison for pointer param (#2428)

JasperNV (1):
      spirv-opt: Behave a bit better in the face of unknown instructions (#2487)

Jeff Bolz (1):
      Add validation for SPV_NV_cooperative_matrix (#2404)

Paul Thomson (8):
      reduce: remove unreferenced blocks pass (#2398)
      Add some val options to reduce (#2401)
      Improve reducer algorithm and other changes (#2472)
      reduce: fix loop to selection dominance query (#2477)
      reduce: fix loop to selection pass for loops with combined header/continue block (#2480)
      reduce: add remove_selection_reduction_opportunity (#2485)
      reduce: miscellaneous fixes (#2494)
      reduce: Add two branch reduction passes (#2507)

Raul Tambre (1):
      Fix use of 'is' operator for comparison (#2547)

Ryan Harrison (19):
      Implement WebGPU specific CFG validation (#2386)
      Add missing DepthGreater case to Fragment only check (#2440)
      Add validation for ExecutionMode in WebGPU (#2443)
      Add validation of storage classes for WebGPU (#2446)
      Add --strip-atomic-counter-memory (#2413)
      Convert sampled consumers to being Instructions instead of IDs (#2464)
      Check OpSampledImage is only passed into valid instructions (#2467)
      Add pass to generate needed initializers for WebGPU (#2481)
      Add WebGPU->Vulkan and Vulkan->WebGPU flags in spirv-opt (#2496)
      Add pass to legalize OpVectorShuffle for WebGPU (#2509)
      Implement WebGPU->Vulkan initializer conversion for 'Function' variables (#2513)
      Change validation of memory semantics for OpAtomics* in WebGPU (#2519)
      Validate that SPIR-V binary is encoded as little endian for WebGPU (#2523)
      Remove legacy utility functions (#2530)
      Remove Acquire, Release, and Relaxed from allowed Mem Sem bits for WebGPU (#2526)
      Add support for Private & Output to initializer decompose flag (#2537)
      Remove stale comment (#2542)
      Add validation specific to OpExecutionModeId (#2536)
      Add pass to fix some invalid unreachable blocks for WebGPU (#2563)

Sarah (3):
      In Vulkan, disallow BufferBlock on StorageBuffer variables  (#2380)
      It is invalid to apply both Restrict and Aliased to the same <id> (#2408)
      Validate: (data) Block can't appear within a Block (#2410)

SarahM0 (1):
      Variable pointers cannot be an operand to OpArrayLength

Shahbaz Youssefi (1):
      Fix webgpu header file name in BUILD.gn (#2493)

Steven Perron (25):
      Start SPIRV-Tools 2019.3
      Don't change type of input and output var in dead member elim (#2412)
      Fix OpDot folding of half float vectors. (#2411)
      Non memory object as parameters. (#2415)
      Handle back edges better in dead branch elim. (#2417)
      Use correct option in spvTextToBinary. (#2416)
      Fix python scripts to work with python3 (#2426)
      Removing decorations when doing constant propagation. (#2444)
      Remove duplicates from list of interface IDs in OpEntryPoint instruction (#2449)
      Handle variable pointer in some optimizations (#2490)
      Update CHANGES
      Add fix storage class code. (#2434)
      Fix use of Logf to avoid format security warning (#2498)
      Accept OpBitCast in fix storage class. (#2505)
      Add -fsantize to link flags. (#2506)
      Shorten names of cmake targets (#2531)
      Fix spirv-headers link in the README. (#2516)
      Fix undefined bit shift in sroa. (#2532)
      Change implementation of post order CFG traversal (#2543)
      Fix up type mismatches. (#2545)
      Validate sign of int types. (#2549)
      Make pointers to isomorphic type interchangeable with option. (#2570)
      Update CHANGES
      Handle id overflow in sroa better. (#2582)
      Finalize SPIRV-Tools v2019.3

alan-baker (19):
      Add a test for two back-edges in a continue (#2418)
      Relax function call parameter check (#2448)
      Add option to validate after each pass (#2462)
      Handle function decls in Structured CFG analysis (#2474)
      Validate that OpUnreacahble is not statically reachable (#2473)
      Maintain inst to block mapping in merge return (#2469)
      Fix merge return in the face of breaks (#2466)
      Remove merge assert in block calculation (#2489)
      Handle dead infinite loops in DCE (#2471)
      Change prioritization of unreachable merge and continue (#2460)
      Gate formatless checks on Vulkan env (#2486)
      Remove unreachable block validation (#2525)
      Reduce runtime of array layout checks (#2534)
      ADCE support for SPIR-V 1.4 entry points (#2561)
      Update priv-to-local for SPIR-V 1.4 (#2567)
      Add tests for folding 1.4 selects (#2568)
      Use last version (#2578)
      Do not fold floating point if float controls used (#2569)
      Update instrumentation passes to handle 1.4 interfaces (#2573)

fjhenigman (1):
      Add Linux ASAN bot configs. (#2427)

greg-lunarg (2):
      Bindless Validation: Descriptor Initialization Check (#2419)
      Instrument: Fix load type of pre-existing builtin (#2575)